import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {validateSandbox,assertSandboxTransition} from '../contracts.mjs';
import {prepareRealResearchInput,assessFormalInput,produceFormalCard,formalProducerStatus} from '../formal-producer.mjs';
import {validateContract,sealContract} from '../../src/contracts/validate.mjs';
import {assessSemantics} from '../../p1b/src/semantics.mjs';
import semantics from '../../p1b/config/semantics.v1.json' with {type:'json'};
import {createClosureDataFixture} from '../../tests/fixtures/closure/data-helpers.mjs';
import {buildBrainPacket} from '../../src/closure/export.mjs';
import {importResearchResult,assertDraftTransition} from '../../src/closure/import.mjs';
import {productionGate} from '../../src/baseline/gates.mjs';
const e=JSON.parse(fs.readFileSync(new URL('../../docs/wave-c/evidence.json',import.meta.url)));
const reports=e.artifacts.filter(x=>x.name.endsWith('.report.json')).map(x=>JSON.parse(fs.readFileSync(x.path)));
const x=reports[0];
test('all nine actual sandbox objects match strict schemas and hashes',()=>{for(const r of e.artifacts.filter(x=>/\.(?:input|assessment|report)\.json$/.test(x.name)))assert.equal(validateSandbox(JSON.parse(fs.readFileSync(r.path))).productionGate,false);});
test('all source/license/history/production promotions rejected',()=>{for(const k of ['provider_identity_verified','license_verified','transport_integrity_verified','historical_visibility_proven','productionGate','tradeable','cloud_transfer'])assert.throws(()=>validateSandbox(sealContract({...x,[k]:true})));});
test('extra arbitrary payload and executable field rejected',()=>{assert.throws(()=>validateSandbox(sealContract({...x,order:'BUY'})));assert.throws(()=>validateSandbox(sealContract({...x,probability:'0.8'})));});
test('current cutoff preserves nanosecond ordering',()=>assert.throws(()=>validateSandbox(sealContract({...x,retrieval_cutoff:'2026-10-06T05:00:00.000000001Z',decision_cutoff:'2026-10-06T05:00:00.000000000Z'})),/WAVE_C_CURRENT_CUTOFF_BEFORE_CAPTURE/));
test('sandbox namespace cannot cross strategy',()=>{for(const namespace of ['CORE_40','EVENT_3','RESEARCH_6_18M'])assert.throws(()=>validateSandbox(sealContract({...x,namespace})));});
test('sandbox consumer only permits local display',()=>{assert.equal(assertSandboxTransition(x,'LOCAL_SANDBOX_DISPLAY'),x);for(const target of ['ResearchCard','Candidate','Signal','Approval','OrderIntent','Order','Fill','CLOUD_MODEL'])assert.throws(()=>assertSandboxTransition(x,target));});
test('native contracts reject report as any formal or execution object',()=>{for(const n of ['ResearchCard','CandidateEligibility','SignalEvent','Approval','OrderIntent','Fill'])assert.throws(()=>validateContract(n,x));});
test('formal producer skeleton refuses real sandbox at every stage',()=>{assert.throws(()=>prepareRealResearchInput({packet:x,receipt:x,snapshot:x}));assert.throws(()=>assessFormalInput(x));assert.throws(()=>produceFormalCard(x));assert.deepEqual(formalProducerStatus(),{input_count:0,assessment_count:0,card_count:0,live_stock_receipts:0,productionGate:false,policy:'UNSET_REQUIRED'});});
test('formal producer does not trust self-proclaimed verified receipt',()=>assert.throws(()=>prepareRealResearchInput({packet:{contract_name:'BrainPacket',verification:'VERIFIED'},receipt:{admission:'ADMITTED'},snapshot:{}})));
test('native semantics do not promote real refs or LLM into user approval',()=>{assert.throws(()=>assessSemantics({scope:'SYNTHETIC_SEMANTIC_TEST_ONLY',dimensions:Object.fromEntries(semantics.dimensions.map(k=>[k,'PASS'])),evidence_refs:[{object_id:x.object_id,object_version:1,content_hash:x.content_hash}],hard_block_refs:[],research_card_ref:null}));assert.throws(()=>validateContract('Approval',{...x,actor_type:'LLM',decision:'APPROVE'}));});
test('native signed packet producer rejects sandbox snapshot and receipt',async t=>{const f=await createClosureDataFixture();t.after(()=>f.db.close());const packet=await buildBrainPacket(f);assert.equal(packet.tradeable??false,false);await assert.rejects(()=>buildBrainPacket({...f,snapshot:x}));await assert.rejects(()=>buildBrainPacket({...f,receipt:x}));});
test('native importer and state transitions reject report',async t=>{const f=await createClosureDataFixture();t.after(()=>f.db.close());const packet=await buildBrainPacket(f);await assert.rejects(()=>importResearchResult({...f,packet,result:x}));for(const target of ['SignalEvent','Approval','OrderIntent'])assert.throws(()=>assertDraftTransition(x,target));});
test('unknown actual profile continues to block production',()=>{const p=JSON.parse(fs.readFileSync(new URL('../../config/account-profile.unconfigured.v1.json',import.meta.url)));assert.equal(productionGate(p).allowed,false);for(const r of reports)assert.equal(r.production_eligible,false);});
