import { hashValue, sealContract, reference } from '../src/contracts/validate.mjs';
import { orderTermsHash } from '../src/baseline/gates.mjs';
export const T='2026-10-05T02:00:00Z', LATER='2026-10-05T02:01:00Z', FUTURE='2026-10-05T03:00:00Z';
export const H=hashValue({ fixture:'SYNTHETIC_NOT_PRODUCTION' });
export const R={object_id:'fixture-ref',object_version:1,content_hash:H};
export function base(name) {
  return {contract_name:name,contract_version:'1.0.0',object_id:`synthetic-${name}`,object_version:1,trace_id:'synthetic-trace',content_hash:H,recorded_at:T,business_timezone:'Asia/Shanghai',provenance:{event_time:T,published_at:null,available_at:T,retrieved_at:T,publication_precision:'NOT_APPLICABLE',source_id:'synthetic',source_version:'fixture-v1',source_hash:H,visibility_basis:'SYNTHETIC'},reason_codes:['SYNTHETIC_FIXTURE_ONLY'],invalidation:{status:'ACTIVE',valid_until:FUTURE,invalidated_at:null,conditions:['upstream version/hash changes invalidate'],reason_code:null}};
}
export function accountProfile() {
  return sealContract({...base('AccountProfile'),mode:'DEV',account_id:'synthetic-account',profile_kind:'UNCONFIGURED',currency:'CNY',settings:{capital_cents:'UNSET_REQUIRED',target_order_cents:'UNSET_REQUIRED',max_positions:'UNSET_REQUIRED',max_single_trade_loss_bps:'UNSET_REQUIRED',max_sector_exposure_bps:'UNSET_REQUIRED',daily_loss_limit_cents:'UNSET_REQUIRED',max_portfolio_drawdown_bps:'UNSET_REQUIRED',margin_allowed:'UNSET_REQUIRED',monthly_trade_frequency:'UNSET_REQUIRED',strategy_budget_cents:{CORE_40:'UNSET_REQUIRED',EVENT_3:'UNSET_REQUIRED'}},broker_costs:{broker_id:'UNSET_REQUIRED',commission_rate:'UNSET_REQUIRED',minimum_commission_cents:'UNSET_REQUIRED',commission_scope:'UNSET_REQUIRED',exchange_fee_rate:'UNSET_REQUIRED',exchange_fee_included:'UNSET_REQUIRED',other_fee_rate:'UNSET_REQUIRED',other_fee_included:'UNSET_REQUIRED',stamp_tax_sell_rate:'UNSET_REQUIRED',statutory_rate_source:'UNSET_REQUIRED',statutory_rate_verified_at:'UNSET_REQUIRED',effective_from:'UNSET_REQUIRED',effective_to:'UNSET_REQUIRED',slippage_base_bps:'UNSET_REQUIRED',slippage_stress_bps:'UNSET_REQUIRED',rounding_mode:'UNSET_REQUIRED',configuration_source:'UNSET_REQUIRED'},user_risk_policy_version:'UNSET_REQUIRED',broker_capability_verified:false,cost_reconciliation_passed:false,program_trading_compliance_checked:false,paper_acceptance_passed:false,kill_switch_test_passed:false,execution_mode:'HUMAN_CONFIRM',auto_execute:false});
}
export function envelope(overrides={}) {
  const payload={title:'visible synthetic evidence',price:'10'};
  return sealContract({...base('DataEnvelope'),entity_id:'synthetic-entity',data_kind:'ANNOUNCEMENT',symbols:['SSE:600000'],raw_uri:'fixture:synthetic',raw_hash:H,payload,payload_hash:hashValue(payload),data_quality:'PASS',adjustment:'NOT_APPLICABLE',adjustment_version:'NOT_APPLICABLE',source_revision:'fixture-v1',...overrides});
}
export function examples() {
  const scope={mode:'DEV',account_id:'synthetic-account',strategy_id:'CORE_40'}, symbol='SSE:600000';
  const card=sealContract({...base('ResearchCard'),...scope,symbol,snapshot_ref:R,decision_cutoff:T,grade:'A',research:{thesis:'Synthetic thesis',strongest_counterevidence:'Synthetic countercase',unknowns:['Unverified fixture assumptions'],evidence_refs:[R],horizon_months:{minimum:6,maximum:18}},price:{reference_price:'10',entry_rules:[],no_trade_rules:[]},trade:{target_holding_sessions:{minimum:20,maximum:40},invalidation_rules:[],thesis_invalidation:['Synthetic adverse event'],sizing_policy_version:'synthetic-only',can_produce_order:true},probability:{scenarios:[{name:'up',probability:'1',return_bps:'100'}],calibrated:true,calibration_ref:R,expected_mae_bps:'UNSET_REQUIRED',net_edge_bps:'UNSET_REQUIRED',edge_policy_version:'synthetic-only'},scores:Object.fromEntries(['fundamental','sector','catalyst','trend','valuation','liquidity','evidence','risk','research','quality','timing','raw','final'].map(k=>[k,'UNSET_REQUIRED'])),scoring_policy_version:'synthetic-only',hard_blocks:[],rule_version:'synthetic-only'});
  const signal=sealContract({...base('SignalEvent'),...scope,symbol,card_ref:reference(card),rule_version:card.rule_version,signal_type:'CORE_PULLBACK',state:'TRIGGERED',market_data_at:T,triggered_at:T,expires_at:FUTURE,dedupe_key:'CORE_40:SSE:600000:CORE_PULLBACK:synthetic-only'});
  const profile=accountProfile();
  const cost=sealContract({...base('CostEstimate'),...scope,symbol,side:'BUY',quantity:100,price:'10',notional_cents:'100000',fees:{commission_cents:'123',exchange_cents:'0',other_cents:'0',stamp_cents:'0',slippage_cents:'0'},total_cost_cents:'123',round_trip_cost_bps:'UNSET_REQUIRED',cost_model_version:'synthetic-only',account_profile_ref:reference(profile),cost_config_hash:H,config_provenance:'SYNTHETIC_NOT_PRODUCTION',slippage_treatment:'INCLUDED_IN_EXECUTION_PRICE',estimated_at:T,expires_at:FUTURE});
  const decisionApproval=sealContract({...base('Approval'),...scope,object_id:'synthetic-decision-approval',actor_type:'HUMAN_USER',actor_id:'fixture-user',channel:'USER_UI',phase:'DECISION_APPROVAL',decision:'USER_APPROVED',card_ref:reference(card),signal_ref:reference(signal),cost_ref:null,order_terms_hash:null,account_snapshot_hash:H,approved_at:T,expires_at:FUTURE});
  let order=sealContract({...base('OrderIntent'),...scope,symbol,side:'BUY',quantity:100,order_type:'LIMIT',limit_price:'10',trade_date:'2026-10-05',card_ref:reference(card),signal_ref:reference(signal),decision_approval_ref:reference(decisionApproval),final_confirmation_ref:null,cost_ref:reference(cost),account_snapshot_hash:H,client_order_id:'synthetic-order',prepared_at:T,expires_at:FUTURE,status:'PREPARED',production_execution_enabled:false});
  const confirmation=sealContract({...base('Approval'),...scope,object_id:'synthetic-final-confirmation',actor_type:'HUMAN_USER',actor_id:'fixture-user',channel:'USER_UI',phase:'FINAL_ORDER_CONFIRMATION',decision:'USER_APPROVED',card_ref:reference(card),signal_ref:reference(signal),cost_ref:reference(cost),order_terms_hash:orderTermsHash(order),account_snapshot_hash:H,approved_at:T,expires_at:FUTURE});
  order=sealContract({...order,final_confirmation_ref:reference(confirmation),status:'CONFIRMED'});
  const data=envelope();
  const snapshot=sealContract({...base('SnapshotManifest'),snapshot_id:'synthetic-snapshot',decision_cutoff:T,data_hash:hashValue([data]),evidence_refs:[reference(data)],rules_hash:H,scope:'SYNTHETIC',excluded_metadata_exported:false,frozen_at:T});
  const feature=sealContract({...base('FeatureSet'),symbol,trade_date:'2026-10-05',strategy_id:'CORE_40',snapshot_ref:reference(snapshot),decision_cutoff:T,feature_version:'synthetic-v1',features:{ma20:{value:'10',unit:'CNY_PER_SHARE',quality:'VALID'}},data_quality:'PASS'});
  const all={
    SecurityIdentity:sealContract({...base('SecurityIdentity'),symbol,exchange:'SSE',security_code:'600000',name:'Synthetic identity',board:'MAIN',security_type:'STOCK',lot_size:100,tick_size:'0.01',status:'ACTIVE',st_flag:false,listed_at:null,delisted_at:null,effective_from:T,effective_to:null,official_status_verified:false}),
    DataEnvelope:data,SnapshotManifest:snapshot,FeatureSet:feature,AccountProfile:profile,CostEstimate:cost,ResearchCard:card,
    BrainPacket:sealContract({...base('BrainPacket'),...scope,request_type:'INITIAL_RESEARCH',snapshot_ref:reference(snapshot),decision_cutoff:T,evidence:[data],candidate_refs:[],card_ref:null,signal_ref:null,transfer_mode:'MANUAL_EXPORT',model_review:{decision:'APPROVE',origin:'LLM',max_notional_cents:'UNSET_REQUIRED',expires_at:FUTURE,reason_codes:['UNSET_REQUIRED_CONFIG']},contains_account_identity_or_credentials:false}),
    CandidateEligibility:sealContract({...base('CandidateEligibility'),...scope,symbol,card_ref:reference(card),feature_ref:reference(feature),cost_ref:null,grade:'A',tradeable:false,hard_blocks:['EDGE_NOT_VERIFIED'],gate_status:'BLOCKED',admission_policy_version:'UNSET_REQUIRED',evaluated_at:T}),
    SignalEvent:signal,Approval:decisionApproval,OrderIntent:order,
    Fill:sealContract({...base('Fill'),...scope,symbol,side:'BUY',quantity:100,price:'10',notional_cents:'100000',fees:cost.fees,order_ref:reference(order),approval_ref:reference(confirmation),cost_model_version:'synthetic-only',broker_fill_id:'synthetic-fill',executed_at:T,execution_source:'SYNTHETIC',slippage_treatment:'INCLUDED_IN_EXECUTION_PRICE'}),
    LedgerEntry:sealContract({...base('LedgerEntry'),...scope,currency:'CNY',entry_type:'FILL',symbol,fill_ref:R,cash_delta_cents:'-100123',quantity_delta:100,account_cash_after_cents:'0',position_quantity_after:100,effective_at:T,sequence:1,previous_entry_hash:null}),
    BacktestResult:sealContract({...base('BacktestResult'),...scope,snapshot_ref:reference(snapshot),data_hash:snapshot.data_hash,strategy_config_hash:H,cost_model_version:'synthetic-only',code_version:'p0-fixture',scenario:'BASE',mae_resolution:'1D',started_at:T,finished_at:T,metrics:{gross_pnl_cents:'0',net_pnl_cents:'0',fees_cents:'0',slippage_cents:'0',trade_count:0,max_drawdown_bps:'0',mfe_bps:'0',mae_bps:'0',by_grade:{},by_signal:{},oos_status:'SYNTHETIC'}}),
    AuditEvent:sealContract({...base('AuditEvent'),mode:'DEV',account_id:null,strategy_id:null,actor_type:'SERVICE',actor_id:'fixture-service',action:'SYNTHETIC_TEST',target_ref:null,before_hash:null,after_hash:null,previous_event_hash:null,occurred_at:T,model_review_is_authorization:false}),
  };
  return {all,chain:{card,signal,decisionApproval,confirmation,order,cost,now:T,currentAccountSnapshotHash:H,authority:{actor_type:'HUMAN_USER',actor_id:'fixture-user',verified_approval_hashes:new Set([decisionApproval.content_hash,confirmation.content_hash])}}};
}
