-- Lossless storage boundary for frozen wire contracts; not a trading dispatcher.
SET TIME ZONE 'UTC';
CREATE TABLE contract_records (
  contract_name TEXT NOT NULL CHECK(contract_name IN (
    'SecurityIdentity','DataEnvelope','SnapshotManifest','FeatureSet','AccountProfile',
    'CostEstimate','ResearchCard','BrainPacket','CandidateEligibility','SignalEvent',
    'Approval','OrderIntent','Fill','LedgerEntry','BacktestResult','AuditEvent')),
  contract_version TEXT NOT NULL CHECK(contract_version='1.0.0'),
  object_id TEXT NOT NULL CHECK(length(object_id)>0),
  object_version positive_version NOT NULL,
  content_hash sha256_digest NOT NULL,
  trace_id TEXT NOT NULL CHECK(length(trace_id)>0),
  recorded_at TIMESTAMPTZ NOT NULL,
  business_timezone TEXT NOT NULL CHECK(business_timezone='Asia/Shanghai'),
  mode execution_mode,
  account_id TEXT,
  strategy_id strategy_namespace,
  event_time TIMESTAMPTZ NOT NULL,
  published_at TEXT,
  publication_precision TEXT NOT NULL CHECK(publication_precision IN ('SECOND','DATE_ONLY','NOT_APPLICABLE','UNKNOWN')),
  available_at TIMESTAMPTZ NOT NULL,
  retrieved_at TIMESTAMPTZ NOT NULL,
  source_id TEXT NOT NULL,
  source_version TEXT NOT NULL,
  source_hash sha256_digest NOT NULL,
  visibility_basis TEXT NOT NULL CHECK(visibility_basis IN ('OBSERVED_AT_TIME','HISTORICAL_AVAILABILITY_RECONSTRUCTION','DERIVED','SYNTHETIC')),
  reason_codes JSONB NOT NULL CHECK(jsonb_typeof(reason_codes)='array'),
  fixture_kind TEXT NOT NULL CHECK(fixture_kind IN ('SYNTHETIC','LEGACY')),
  ingestion_status TEXT NOT NULL DEFAULT 'QUARANTINED' CHECK(ingestion_status='QUARANTINED'),
  payload JSONB NOT NULL CHECK(jsonb_typeof(payload)='object'),
  PRIMARY KEY(contract_name,object_id,object_version),
  UNIQUE(contract_name,object_id,object_version,content_hash),
  CHECK(available_at<=retrieved_at),
  CHECK(payload->>'contract_name'=contract_name AND payload->>'contract_version'=contract_version),
  CHECK(payload->>'object_id'=object_id AND (payload->>'object_version')::NUMERIC=object_version),
  CHECK(payload->>'content_hash'=content_hash AND payload->>'trace_id'=trace_id),
  CHECK(payload->>'business_timezone'=business_timezone),
  CHECK((payload->>'recorded_at')::TIMESTAMPTZ=recorded_at),
  CHECK((payload->>'mode') IS NOT DISTINCT FROM mode),
  CHECK((payload->>'account_id') IS NOT DISTINCT FROM account_id),
  CHECK((payload->>'strategy_id') IS NOT DISTINCT FROM strategy_id),
  CHECK((payload->'provenance'->>'event_time')::TIMESTAMPTZ=event_time),
  CHECK((payload->'provenance'->>'published_at') IS NOT DISTINCT FROM published_at),
  CHECK(payload->'provenance'->>'publication_precision'=publication_precision),
  CHECK((payload->'provenance'->>'available_at')::TIMESTAMPTZ=available_at),
  CHECK((payload->'provenance'->>'retrieved_at')::TIMESTAMPTZ=retrieved_at),
  CHECK(payload->'provenance'->>'source_id'=source_id),
  CHECK(payload->'provenance'->>'source_version'=source_version),
  CHECK(payload->'provenance'->>'source_hash'=source_hash),
  CHECK(payload->'provenance'->>'visibility_basis'=visibility_basis),
  CHECK(payload->'reason_codes'=reason_codes),
  CHECK(contract_name NOT IN ('CostEstimate','CandidateEligibility','SignalEvent','Approval','OrderIntent','Fill','LedgerEntry','BacktestResult') OR strategy_id IN ('CORE_40','EVENT_3'))
);
CREATE TRIGGER immutable_history BEFORE UPDATE OR DELETE ON contract_records FOR EACH ROW EXECUTE FUNCTION reject_history_mutation();
CREATE TRIGGER immutable_truncate BEFORE TRUNCATE ON contract_records FOR EACH STATEMENT EXECUTE FUNCTION reject_history_mutation();
COMMENT ON TABLE contract_records IS 'Canonical wire contracts, validated/hash-checked by importer. Fixture-only P0 entry point; no normalized trading writes or execution authority. published_at TEXT preserves explicit DATE_ONLY/UNKNOWN without inventing timestamp.';
