import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import Ajv from 'ajv/dist/2020.js';
import {canonical,hashValue,validateContract} from '../../src/contracts/validate.mjs';
import {assessSemantics} from '../../p1b/src/semantics.mjs';
import semantics from '../../p1b/config/semantics.v1.json' with {type:'json'};
import {createClosureDataFixture} from '../../tests/fixtures/closure/data-helpers.mjs';
import {buildBrainPacket} from '../../src/closure/export.mjs';
import {assertDraftTransition,importResearchResult} from '../../src/closure/import.mjs';
import {productionGate} from '../../src/baseline/gates.mjs';
import {produceFixture} from '../../overnight/fixture/chain.mjs';
const schema=JSON.parse(fs.readFileSync(new URL('../../contracts/wave-b/AdmissionCandidate.schema.json',import.meta.url)));
const validate=new Ajv({strict:true,allErrors:true}).compile(schema);
const evidence=JSON.parse(fs.readFileSync(new URL('../../docs/wave-b/evidence.json',import.meta.url)));
const candidate=JSON.parse(fs.readFileSync(evidence.artifacts.find(x=>x.object==='candidate').path));
const mutate=fn=>{const x=structuredClone(candidate);fn(x);return x;};
test('actual quarantine candidate matches strict diagnostic schema and hash',()=>{assert.equal(validate(candidate),true,JSON.stringify(validate.errors));const {content_hash,...b}=candidate;assert.equal(content_hash,hashValue(b));assert.equal(candidate.fixture,false);});
test('schema rejects all provider, license, historical and production escalation',()=>{for(const k of ['provider_identity_verified','license_verified','transport_integrity_verified','historical_visibility_proven','productionGate'])assert.equal(validate(mutate(x=>x[k]=true)),false);});
test('schema rejects research output counts and extra authority fields',()=>{assert.equal(validate(mutate(x=>x.body.counts.real_cards=1)),false);assert.equal(validate(mutate(x=>x.receipt={admission:'ADMITTED'})),false);});
test('schema rejects cross-strategy namespace and body market widening',()=>{for(const s of ['EVENT_3','RESEARCH_6_18M'])assert.equal(validate(mutate(x=>x.namespace=s)),false);assert.equal(validate(mutate(x=>x.body.authorization_scope.symbols.push('000001.SZ'))),false);});
test('native ResearchAssessment semantic producer rejects real quarantine refs',()=>{const input={dimensions:Object.fromEntries(semantics.dimensions.map(k=>[k,'PASS'])),evidence_refs:[{object_id:'wave-b:real-quarantine',object_version:1,content_hash:candidate.content_hash}],hard_block_refs:[],research_card_ref:null,scope:'SYNTHETIC_SEMANTIC_TEST_ONLY'};assert.throws(()=>assessSemantics(input),/P1B_CLOUD_EVIDENCE_UNTRUSTED/);});
test('native ResearchCard contract does not accept candidate as card',()=>assert.throws(()=>validateContract('ResearchCard',candidate)));
test('native CandidateEligibility and Signal contracts reject quarantine object',()=>{for(const n of ['CandidateEligibility','SignalEvent'])assert.throws(()=>validateContract(n,candidate));});
test('native signed BrainPacket producer rejects quarantine snapshot before writes',async t=>{const f=await createClosureDataFixture();t.after(()=>f.db.close());const packet=await buildBrainPacket(f);assert.equal(packet.can_produce_order,false);await assert.rejects(()=>buildBrainPacket({...f,snapshot:candidate}));await assert.rejects(()=>buildBrainPacket({...f,receipt:candidate}));});
test('native research import and transitions reject real quarantine without cost or approval bypass',async t=>{const f=await createClosureDataFixture();t.after(()=>f.db.close());const packet=await buildBrainPacket(f);await assert.rejects(()=>importResearchResult({...f,packet,result:candidate}));for(const n of ['CandidateEligibility','SignalEvent','Approval','OrderIntent'])assert.throws(()=>assertDraftTransition(candidate,n));});
test('unchanged fixture wrapper rejects arbitrary real input before model work',async()=>{await assert.rejects(()=>produceFixture({directory:'SYNTHETIC_UNUSED',fixture_case:'BASE',real_input:candidate}),/OVERNIGHT_REAL_INPUT_FORBIDDEN/);});
test('unknown actual configuration continues to block production despite candidate readiness',()=>{const p=JSON.parse(fs.readFileSync(new URL('../../config/account-profile.unconfigured.v1.json',import.meta.url)));assert.equal(productionGate(p).allowed,false);assert.equal(candidate.body.real_net_edge,'UNSET_REQUIRED');assert.equal(candidate.body.real_sizing,'UNSET_REQUIRED');});
