// Twelve original diagnostic assertions, preserved under the new exact-root verifier.
// The original source/tests remain unchanged and pinned in EvidenceRootBinding1.0.0.
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {hashValue} from '../../src/contracts/validate.mjs';
import {root,verifyHistoricalDiagnostic as verifyAdmissionVerification} from '../verify.mjs';
import {verifyDiagnosticRelease} from '../../tushare-admission/parent/verify.mjs';
const read=()=>JSON.parse(fs.readFileSync(path.join(root,'docs/tushare-admission/Gate.json'),'utf8'));
const seal=r=>{const {content_hash,...b}=r;return {...b,content_hash:hashValue(b)};};
test('diagnostic Gate binds real nonsecret public originals and missing-credential evidence',()=>{assert.equal(verifyAdmissionVerification(read()).actual_account_tier,15000);verifyDiagnosticRelease();});
test('public quota or API success cannot mint any of nine permissions',()=>{for(const k of Object.keys(read().permissions)){const r=read();r.permissions[k]=true;assert.throws(()=>verifyAdmissionVerification(seal(r)),/SCHEMA_INVALID/);}});
test('tier is15000 Owner assertion; monthly expiry cannot be fabricated from annual table',()=>{for(const [k,v] of [['actual_account_tier',5000],['account_tier_evidence_basis','OFFICIAL_VERIFIED'],['actual_expiration','2027-10-05']]){const r=read();r[k]=v;assert.throws(()=>verifyAdmissionVerification(seal(r)),/SCHEMA_INVALID/);}});
test('three-security CORE namespace excludes whole-market, fourth stock or EVENT_3',()=>{for(const change of [r=>r.stock_scope.push('000001.SZ'),r=>r.stock_scope=[],r=>r.namespace='EVENT_3']){const r=read();change(r);assert.throws(()=>verifyAdmissionVerification(seal(r)),/SCHEMA_INVALID/);}});
test('uncollected or unlicensed evidence cannot close C12 or create Snapshot B',()=>{for(const change of [r=>r.closed_condition_ids=['C12'],r=>r.snapshot_B='READY',r=>r.category_matrix.RAW_BARS_1D.coverage_complete=true]){const r=read();change(r);assert.throws(()=>verifyAdmissionVerification(seal(r)),/SCHEMA_INVALID/);}});
test('historical availability and fake registered lineages are denied even with resealed hash',()=>{for(const change of [r=>r.historical_visibility_proven=true,r=>r.category_matrix.FINANCIAL_REVISIONS.historical_visibility_proven=true,r=>r.category_matrix.RAW_BARS_1D.receipt_ref={object_id:'forged',object_version:1,content_hash:'sha256:'+'a'.repeat(64)}]){const r=read();change(r);assert.throws(()=>verifyAdmissionVerification(seal(r)),/SCHEMA_INVALID/);}});
test('blocked transport means zero queries, not observed denial or invented rows',()=>{const r=read();r.category_matrix.RAW_BARS_1D.state='ENTITLEMENT_NOT_GRANTED';r.category_matrix.RAW_BARS_1D.authenticated_request_count=1;assert.throws(()=>verifyAdmissionVerification(seal(r)),/SCHEMA_INVALID/);});
test('unknown entitlement cannot be called denied or supported without an actual query',()=>{for(const state of ['ENTITLEMENT_NOT_GRANTED','TECHNICAL_ACCESS_OBSERVED_ONLY']){const r=read();r.category_matrix.RAW_BARS_1D.state=state;assert.throws(()=>verifyAdmissionVerification(seal(r)),/SCHEMA_INVALID/);}});
test('unexpected secret-bearing key cannot enter diagnostic evidence contract',()=>{const r=read();r.credential_lookup.token='SYNTHETIC_TEST_ONLY';assert.throws(()=>verifyAdmissionVerification(seal(r)),/SCHEMA_INVALID/);});
test('credential presence, lookup result and provided reference must agree',()=>{for(const change of [r=>r.credential_lookup.presence=true,r=>r.credential_lookup.reference_provided=true,r=>r.credential_lookup.result='PRESENT_IN_MEMORY_ONLY']){const r=read();change(r);assert.throws(()=>verifyAdmissionVerification(seal(r)),/SCHEMA_INVALID/);}});
test('old credential, missing supplier HTTPS and caller HTTP exception cannot unblock probe',()=>{for(const change of [r=>r.credential_rotation.old_credential_permitted=true,r=>r.credential_rotation.owner_rotation_confirmed=true,r=>r.transport_gate.authenticated_request_allowed=true,r=>r.transport_gate.credential_lookup_allowed=true,r=>r.transport_gate.owner_http_exception=true,r=>r.transport_gate.tls_bypass_allowed=true,r=>r.source_id='TUSHARE_OFFICIAL_DIRECT']){const r=read();change(r);assert.throws(()=>verifyAdmissionVerification(seal(r)),/SCHEMA_INVALID/);}});
test('report and evidence tampering rejected; secret-store paths are outside evidence allowlist',()=>{let r=read();r.trace_id='tampered';assert.throws(()=>verifyAdmissionVerification(r),/HASH_INVALID/);r=read();r.evidence_refs[0].sha256='sha256:'+'0'.repeat(64);assert.throws(()=>verifyAdmissionVerification(seal(r)),/EVIDENCE_MISMATCH/);r=read();r.evidence_refs[0].path='/Users/qiushi/.ssh/id_rsa';assert.throws(()=>verifyAdmissionVerification(seal(r)),/PATH_UNAPPROVED/);});
