import {readFile} from 'node:fs/promises';
import {hashValue,sealContract,reference,requireThat,validateContract} from '../contracts/validate.mjs';
import {ingestSourceObservation,registerSecurity,ingestCalendar,ingestBar,freezeDataSnapshot,ref} from '../data/index.mjs';
import {sealReferenceObject} from '../paper/index.mjs';
export const experimentFixture=JSON.parse(await readFile(new URL('../../tests/fixtures/p1a-replay/experiment.json',import.meta.url),'utf8'));
const unknownProfile=JSON.parse(await readFile(new URL('../../config/account-profile.unconfigured.v1.json',import.meta.url),'utf8'));
export function syntheticAccount(fixture=experimentFixture){
  const at=fixture.decision_cutoff;
  const p={...unknownProfile,object_id:'SYNTHETIC_P1A_ACCOUNT_PROFILE',object_version:1,trace_id:'SYNTHETIC_FIXED_INPUT_TRACE',recorded_at:at,mode:'PAPER',account_id:'SYNTHETIC_P1A_ACCOUNT',profile_kind:'SYNTHETIC_FIXTURE',notes:'Uncalibrated P1-A offline acceptance fixture; no production or legacy defaults.',provenance:{event_time:at,published_at:null,available_at:at,retrieved_at:at,publication_precision:'NOT_APPLICABLE',source_id:'SYNTHETIC_FIXTURE',source_version:'p1a-fixture-1',source_hash:hashValue(fixture),visibility_basis:'SYNTHETIC'},reason_codes:['SYNTHETIC_FIXTURE_ONLY'],invalidation:{status:'ACTIVE',valid_until:null,invalidated_at:null,conditions:['fixture input changed'],reason_code:null},settings:{capital_cents:fixture.opening_cash_cents,target_order_cents:'200000',max_positions:7,max_single_trade_loss_bps:'123',max_sector_exposure_bps:'4567',daily_loss_limit_cents:'12345',max_portfolio_drawdown_bps:'789',margin_allowed:false,monthly_trade_frequency:12,strategy_budget_cents:{CORE_40:'650000',EVENT_3:'500000'}},broker_costs:{broker_id:'SYNTHETIC_NO_BROKER',commission_rate:'0.0008',minimum_commission_cents:'150',commission_scope:'PER_ORDER',exchange_fee_rate:'0.00004',exchange_fee_included:false,other_fee_rate:'0.00003',other_fee_included:false,stamp_tax_sell_rate:'0.0009',statutory_rate_source:'SYNTHETIC_UNCALIBRATED',statutory_rate_verified_at:at,effective_from:'2025-01-01',effective_to:'2025-12-31',slippage_base_bps:'3',slippage_stress_bps:'15',rounding_mode:'HALF_UP',configuration_source:'SYNTHETIC_TEST_ONLY'},user_risk_policy_version:'SYNTHETIC_UNCALIBRATED',broker_capability_verified:false,cost_reconciliation_passed:false,program_trading_compliance_checked:false,paper_acceptance_passed:false,kill_switch_test_passed:false};
  return validateContract('AccountProfile',sealContract(p));
}
export async function buildReplayData(db,{fixture=experimentFixture,byteMutation=false}={}){
  const observation=async(id,payload,at)=>{const source={source_id:'SYNTHETIC_P1A_REPLAY',source_version:'fixture-source-1',source_class:'SYNTHETIC',license_type:'SYNTHETIC_TEST',allowed_use:['SYNTHETIC_TEST'],terms_version:'SYNTHETIC_TEST_ONLY',data_class:'SYNTHETIC',allowed_hosts:[],clock_policy:{type:'SOURCE_FIELD',available_path:'available_at',published_path:'published_at'}};return ingestSourceObservation(db,{rawBytes:Buffer.from(JSON.stringify({published_at:at,available_at:at,fact:payload})+(byteMutation&&id==='source:replay-bar'?' ':'')),source,object_id:id,payload,trace_id:'SYNTHETIC_FIXED_INPUT_TRACE',retrieved_at:at,clocks:{event_time:at,published_at:at,publication_precision:'SECOND',clock_proof:{type:'SOURCE_FIELD',available_path:'available_at',published_path:'published_at'}}});};
  const early='2025-04-01T00:00:00+08:00';
  const securitySource=await observation('source:replay-security',{fixture_kind:'SYNTHETIC',symbol:'600000',original_symbol:'sh.600000',name:'Synthetic replay security',listing_status:'LISTED',list_date:'2020-01-01',delist_date:null,board:'MAIN',lot_size:100,st_status:'NORMAL',suspension_status:'TRADING',effective_from:early,effective_to:null},early);
  const securityRecord=await registerSecurity(db,{observation:securitySource,security_id:'synthetic:replay-security',original_symbol:'sh.600000',listing_status:'LISTED',list_date:'2020-01-01',board:'MAIN',lot_size:100,st_status:'NORMAL',suspension_status:'TRADING',effective_from:early,name:'Synthetic replay security'});
  const dates=new Set(['2025-04-09',...fixture.sessions]),days=[];
  for(let ms=Date.parse('2025-04-09T00:00:00Z');ms<=Date.parse('2025-06-11T00:00:00Z');ms+=86400000){const date=new Date(ms).toISOString().slice(0,10);days.push({date,status:dates.has(date)?'TRADING':'NON_TRADING',sessions:dates.has(date)?[{kind:'AM',open:'09:30:00',close:'11:30:00'},{kind:'PM',open:'13:00:00',close:'15:00:00'}]:[],reason:'SYNTHETIC_EXPLICIT_SESSION_SET'});}
  const calendarSource=await observation('source:replay-calendar',{fixture_kind:'SYNTHETIC',days,exchange:'SSE',coverage_start:'2025-04-09',coverage_end:'2025-06-11',session_rule_version:'SYNTHETIC_SESSION_V1'},early);
  const calendarRecord=await ingestCalendar(db,{observation:calendarSource,calendar_id:'synthetic:replay-calendar',exchange:'SSE',days,coverage_start:'2025-04-09',coverage_end:'2025-06-11',session_rule_version:'SYNTHETIC_SESSION_V1'});
  const barPayload={fixture_kind:'SYNTHETIC',canonical_symbol:'SSE:600000',trade_date:'2025-04-09',open:'10',high:'10.2',low:'9.8',close:'10',preclose:'10',volume:123400,amount_cents:'123400000',price_basis:'RAW'};
  const barSource=await observation('source:replay-bar',barPayload,'2025-04-09T15:01:00+08:00');
  const bar=await ingestBar(db,{observation:barSource,security:securityRecord,calendar:calendarRecord,...barPayload,object_id:'synthetic:replay-bar'});
  const snapshot=await freezeDataSnapshot(db,{root_refs:[ref(bar)],decision_cutoff:fixture.decision_cutoff,feature_version:fixture.feature_version,rules_hash:hashValue(fixture.rule_version),scope:'SYNTHETIC',trace_id:'SYNTHETIC_FIXED_INPUT_TRACE',frozen_at:fixture.decision_cutoff});requireThat(snapshot.status==='FROZEN','REPLAY_SNAPSHOT_NOT_FROZEN');
  const feature=sealContract({contract_name:'FeatureSet',contract_version:'1.0.0',object_id:'synthetic:replay-feature',object_version:1,trace_id:'SYNTHETIC_FIXED_INPUT_TRACE',recorded_at:fixture.decision_cutoff,business_timezone:'Asia/Shanghai',provenance:{event_time:fixture.decision_cutoff,published_at:null,available_at:fixture.decision_cutoff,retrieved_at:fixture.decision_cutoff,publication_precision:'NOT_APPLICABLE',source_id:'SYNTHETIC_P1A_REFERENCE_FEATURE',source_version:fixture.feature_version,source_hash:bar.content_hash,visibility_basis:'DERIVED'},reason_codes:['SYNTHETIC_FIXTURE_ONLY'],invalidation:{status:'ACTIVE',valid_until:null,invalidated_at:null,conditions:['snapshot or feature version changes'],reason_code:null},symbol:bar.canonical_symbol,trade_date:'2025-04-09',strategy_id:'CORE_40',snapshot_ref:reference(snapshot.manifest),decision_cutoff:fixture.decision_cutoff,feature_version:fixture.feature_version,features:{last_close:{value:bar.payload.close,unit:'CNY_PER_SHARE',quality:'VALID'}},data_quality:'PASS'});validateContract('FeatureSet',feature);
  // Explicit projection binds source registry/calendar hashes, rather than a second canonical identity.
  const calendar=sealReferenceObject({version:`${calendarRecord.object_id}@${calendarRecord.object_version}`,sessions:fixture.sessions,available_at:calendarRecord.available_at,source:{kind:'SYNTHETIC_FIXTURE',source_hash:calendarRecord.content_hash},source_ref:ref(calendarRecord)});
  const security=sealReferenceObject({security_id:securityRecord.security_id,canonical_symbol:securityRecord.canonical_symbol,original_symbol:securityRecord.original_symbol,lot_size:securityRecord.payload.lot_size,status:'ACTIVE',suspended:false,tradeable:true,version:`${securityRecord.object_id}@${securityRecord.object_version}`,available_at:securityRecord.available_at,source_ref:ref(securityRecord)});
  return {snapshot,feature,calendar,security,bar,calendarRecord,securityRecord,account_profile:syntheticAccount(fixture)};
}
