import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {createCollector,createAdmissionService,validateClock,compareSnapshots,CATEGORIES} from '../src/core.mjs';
import {captureSpecs,normalizeCapture} from '../src/providers.mjs';
import {seal,hash,sha,makeAuthority,verifyProof,assertPublic,refOf,validate} from '../src/contracts.mjs';

// Pure structure/clock arithmetic fixtures. They cannot create observed admission.
const at='2026-10-05T12:00:00.123Z', spec=captureSpecs()[1];
const clock=()=>seal({contract_name:'ClockEvidence',contract_version:'1.0.0',object_id:'synthetic-clock',object_version:1,trace_id:'synthetic-clock',business_timezone:'Asia/Shanghai',scope:'SYNTHETIC_TEST_ONLY',event_time:null,event_date:null,business_effective_at:'2026-10-08',published_at:null,published_date:'2026-09-17',published_precision:'DATE_ONLY',available_at:at,retrieved_at:at,observation_event_at:at,effective_from:null,effective_to:null,availability_basis:'ACTUAL_RETRIEVAL_BOUNDARY',historical_visibility_proven:false});
const change=(x,f)=>{const y=structuredClone(x);f(y);return seal(y);};
test('clock DATE_ONLY keeps no instant and future business date is not future visibility',()=>validateClock(clock(),at));
test('fabricated midnight for DATE_ONLY is rejected',()=>assert.throws(()=>validateClock(change(clock(),x=>x.published_at='2026-09-17T00:00:00+08:00'),at)));
test('earlier fake available_at and update-window substitution are rejected',()=>{for(const value of ['2026-09-30T15:00:00+08:00','2026-09-30T16:00:00+08:00'])assert.throws(()=>validateClock(change(clock(),x=>x.available_at=value),at));});
test('cutoff and publication nanosecond boundaries fail closed',()=>{assert.throws(()=>validateClock(clock(),'2026-10-05T12:00:00.122999999Z'));assert.throws(()=>validateClock(change(clock(),x=>{x.published_date=null;x.published_precision='EXACT';x.published_at='2026-10-05T12:00:00.123000001Z';}),at));});
test('historical visibility and unknown precise publication are rejected',()=>{assert.throws(()=>validateClock(change(clock(),x=>x.historical_visibility_proven=true),at));assert.throws(()=>validateClock(change(clock(),x=>x.published_precision='UNKNOWN'),at));});
test('minute precision cannot preserve fabricated sub-minute seconds',()=>{const c=change(clock(),x=>{x.published_date=null;x.published_precision='MINUTE';x.published_at='2026-10-05T11:00:01Z';});assert.throws(()=>validateClock(c,at));validateClock(change(c,x=>x.published_at='2026-10-05T11:00:00Z'),at);});
test('unregistered/forged collector and caller normalizer have no admission authority',()=>{const c=createCollector({specs:captureSpecs()});for(const [collector,normalize] of [[{open:async()=>({record:{scope:'CURRENT_OBSERVED'}})},normalizeCapture],[c,()=>({})]])assert.throws(()=>createAdmissionService({collector,normalize,codeEpoch:'SYNTHETIC_TEST_ONLY'}));});
test('call/apply receivers cannot replace frozen lexical validators or leak unregistered payload',async()=>{const collector=createCollector({specs:captureSpecs()}),s=createAdmissionService({collector,normalize:normalizeCapture,codeEpoch:'SYNTHETIC_TEST_ONLY_UNREGISTERED'});let hooks=0;const receiver={verifyPacket:async()=>{hooks++;return true;},verifyReceipt:async()=>{hooks++;return true;},packet:async()=>{hooks++;return {};}};await assert.rejects(()=>s.transfer.call(receiver,{packet:{raw_document:'SYNTHETIC',token:'SYNTHETIC',production_enabled:true}},'LOCAL_REVIEW_ONLY'));await assert.rejects(()=>s.packet.apply(receiver,[{},{}]));await assert.rejects(()=>s.verifyPacket.call(receiver,{packet:{},snapshot:{},receipt:{},use_at:at}));assert.equal(hooks,0);});
test('fixture clock can never be promoted by real facade',async()=>{const c=createCollector({specs:[spec],fixture:true});const h=await c.fixtureCapture({spec,bytes:Buffer.from('SYNTHETIC_TEST_ONLY'),retrieved_at:at});assert.equal((await c.open(h)).record.scope,'SYNTHETIC_TEST_ONLY');assert.throws(()=>createAdmissionService({collector:c,normalize:normalizeCapture,codeEpoch:'SYNTHETIC_TEST_ONLY',termsHandle:h}));await assert.rejects(()=>c.fetch(spec));});
test('capture handles are opaque identities and returned buffers cannot alter originals',async()=>{const c=createCollector({specs:[spec],fixture:true}),h=await c.fixtureCapture({spec,bytes:Buffer.from('synthetic'),retrieved_at:at});await assert.rejects(()=>c.open({...h}));const a=await c.open(h);a.bytes.fill(0);a.record.retrieved_at='2000-01-01T00:00:00Z';assert.equal((await c.open(h)).bytes.toString(),'synthetic');assert.equal((await c.open(h)).record.retrieved_at,at);});
test('mutated archived originals fail on every new read',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'slice-fixture-'));try{const c=createCollector({specs:[spec],fixture:true,archiveDirectory:dir}),h=await c.fixtureCapture({spec,bytes:Buffer.from('synthetic'),retrieved_at:at}),r=(await c.open(h)).record;await fs.writeFile(path.join(dir,r.content_hash.slice(7)+'.raw'),'changed');await assert.rejects(()=>c.open(h),/SLICE_RAW_MUTATION/);}finally{await fs.rm(dir,{recursive:true,force:true});}});
test('caller clocks added to real spec are rejected before network access',async()=>{const c=createCollector({specs:captureSpecs()});await assert.rejects(()=>c.fetch({...spec,retrieved_at:'2000-01-01T00:00:00Z'}),/SLICE_SCOPE_MISMATCH/);});
test('secrets, filesystem, future outcome and caller signatures fail closed',()=>{for(const x of [{token:'synthetic'},{title:'Bearer synthetic-value'},{title:'/Users/synthetic/raw'},{future_MAE:1},{title:'future_outcome:99'}])assert.throws(()=>assertPublic(x));const a=makeAuthority(),b=makeAuthority(),x=seal({value:'SYNTHETIC_TEST_ONLY'});x.proof=a.sign(x.content_hash);verifyProof(x,a.publicKeyDer);assert.throws(()=>verifyProof(x,b.publicKeyDer));});
function snapshot(id,facts,sources){return seal({contract_name:'StockSnapshot',contract_version:'1.0.0',object_id:id,object_version:1,trace_id:id,scope:'SYNTHETIC_TEST_ONLY',namespace:'CORE_40',purpose:'LOCAL_CURRENT_OBSERVED_REFERENCE',decision_cutoff:at,observation_refs:[refOf(seal({object_id:'synthetic-observation',object_version:1}))],policy_refs:[refOf(seal({object_id:'synthetic-policy',object_version:1}))],source_hashes:sources,fact_hashes:facts,data_hash:hash({facts,sources}),category_status:Object.fromEntries(CATEGORIES.map(c=>[c,'BLOCKED'])),market_state:'CLOSED',latest_trading_session:null,live_price:null,trade_trigger:false,tradeable:false,historical_visibility_proven:false,completion:'PARTIAL_RESEARCH_ONLY',production_enabled:false});}
test('synthetic A to B preserves independent facts and invalidates dependent features/packet',()=>{const stable=hash('synthetic-stable'),old=hash('synthetic-old'),fresh=hash('synthetic-new'),a=snapshot('synthetic-A',[stable,old],[sha('synthetic-source-A')]),b=snapshot('synthetic-B',[stable,fresh],[sha('synthetic-source-B')]),affected=refOf(seal({object_id:'synthetic-feature',object_version:1})),unaffected=refOf(seal({object_id:'synthetic-independent',object_version:1}));validate('StockSnapshot',a);const r=compareSnapshots(a,b,{featureDependencies:[{feature_ref:affected,fact_hashes:[old]},{feature_ref:unaffected,fact_hashes:[stable]}]});assert.deepEqual(r.unchanged_fact_hashes,[stable]);assert.deepEqual(r.invalidated_feature_refs,[affected]);assert.equal(r.old_packet_invalidated,true);assert.equal(r.source_bytes_changed,true);assert.equal(r.real_post_holiday_proof,false);assert.deepEqual(compareSnapshots(a,a).removed_fact_hashes,[]);assert.equal(compareSnapshots(a,a).snapshot_changed,false);assert.throws(()=>compareSnapshots(a,change(b,x=>x.scope='CURRENT_OBSERVED')));});
