import {canonical,hashValue,requireThat,timestampMs} from '../contracts/validate.mjs';
import {reasons,assertSanitized,validateClosure} from './contracts.mjs';
const queues=new WeakMap(),admissionQueues=new WeakMap();
// Single-process, same-DB-handle ordering for publication versus policy/revocation.
// No claim of server/DB-owner/multi-process isolation. Callback receives no DB capability.
export async function withAdmissionUse(db,operation){requireThat(typeof operation==='function','CLOSURE_IMPORT_INVALID');const pending=(admissionQueues.get(db)??Promise.resolve()).catch(()=>{}).then(operation);admissionQueues.set(db,pending);return pending;}
export async function savePolicy(db,p){validateClosure('SourceAdmissionPolicy',p);await db.query('INSERT INTO p1a_closure.policies(content_hash,policy_json,valid_from,valid_until) VALUES($1,$2::jsonb,$3,$4) ON CONFLICT(content_hash) DO NOTHING',[p.content_hash,canonical(p),p.valid_from,p.valid_until]);requireThat(canonical(await readPolicy(db,p.content_hash))===canonical(p),'CLOSURE_DUPLICATE_CONFLICT');}
export async function readPolicy(db,hash){const{rows}=await db.query('SELECT policy_json FROM p1a_closure.policies WHERE content_hash=$1',[hash]);requireThat(rows.length===1,'CLOSURE_POLICY_UNTRUSTED');return rows[0].policy_json;}
export async function saveReceipt(db,r){validateClosure('AdmissionReceipt',r);await db.query('INSERT INTO p1a_closure.receipts(content_hash,policy_hash,receipt_json,issued_at,expires_at) VALUES($1,$2,$3::jsonb,$4,$5) ON CONFLICT(content_hash) DO NOTHING',[r.content_hash,r.policy_ref.content_hash,canonical(r),r.issued_at,r.expires_at]);requireThat(canonical(await readReceipt(db,r.content_hash))===canonical(r),'CLOSURE_DUPLICATE_CONFLICT');}
export async function readReceipt(db,hash){const{rows}=await db.query('SELECT receipt_json FROM p1a_closure.receipts WHERE content_hash=$1',[hash]);requireThat(rows.length===1,'CLOSURE_RECEIPT_UNKNOWN');return rows[0].receipt_json;}
export async function assertNotRevoked(db,kind,hash,now){timestampMs(now);const{rows}=await db.query('SELECT target_hash FROM p1a_closure.revocations WHERE target_kind=$1 AND target_hash=$2 AND revoked_at<=$3',[kind,hash,now]);requireThat(rows.length===0,kind==='POLICY'?'CLOSURE_POLICY_REVOKED':'CLOSURE_RECEIPT_REVOKED');}
export async function revoke(db,{kind,hash,now,reason_code}){requireThat(['POLICY','RECEIPT'].includes(kind)&&reasons.includes(reason_code),'CLOSURE_IMPORT_INVALID');timestampMs(now);await(kind==='POLICY'?readPolicy(db,hash):readReceipt(db,hash));await db.query('INSERT INTO p1a_closure.revocations VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING',[kind,hash,now,reason_code]);}
export async function closureAudit(db,{chain_id,event_type,event_time,refs=[],reason_codes=[]}){
 requireThat(typeof chain_id==='string'&&/^[A-Za-z0-9:._-]{1,160}$/.test(chain_id)&&['EXPORT_ACCEPTED','EXPORT_REJECTED','IMPORT_COST_ESTIMATED','IMPORT_ACCEPTED','IMPORT_REJECTED','CONSUMER_ACCEPTED','CONSUMER_REJECTED'].includes(event_type)&&Array.isArray(reason_codes)&&reason_codes.every(r=>reasons.includes(r)),'CLOSURE_IMPORT_INVALID');timestampMs(event_time);
 requireThat(Array.isArray(refs)&&refs.every(r=>r&&canonical(Object.keys(r).sort())===canonical(['content_hash','object_id','object_version'])&&typeof r.object_id==='string'&&/^[A-Za-z0-9:._-]{1,200}$/.test(r.object_id)&&Number.isSafeInteger(r.object_version)&&r.object_version>0&&/^sha256:[a-f0-9]{64}$/.test(r.content_hash)),'CLOSURE_IMPORT_INVALID');assertSanitized(refs);
 const run=async()=>{const{rows}=await db.query('SELECT event_hash,sequence FROM p1a_closure.audit WHERE chain_id=$1 ORDER BY sequence DESC LIMIT 1',[chain_id]);const body={chain_id,sequence:rows.length?Number(rows[0].sequence)+1:1,previous_hash:rows[0]?.event_hash??'sha256:'+'0'.repeat(64),event_type,event_time,refs:structuredClone(refs),reason_codes:structuredClone(reason_codes)};const event_hash=hashValue(body);await db.query('INSERT INTO p1a_closure.audit VALUES($1,$2,$3,$4,$5,$6,$7::jsonb)',[event_hash,chain_id,body.sequence,body.previous_hash,event_type,event_time,canonical({...body,event_hash})]);return {...body,event_hash};};
 const pending=(queues.get(db)??Promise.resolve()).catch(()=>{}).then(run);queues.set(db,pending);return pending;
}
