"""Public-source feasibility catalog; access is never historical admission."""
from __future__ import annotations
from .interface import FINANCIAL_START, HISTORY_START, HISTORY_END

API_DOMAINS = {
    'daily': 'PRICE', 'trade_cal': 'CALENDAR', 'stock_basic': 'STATUS',
    'dividend': 'ACTION', 'adj_factor': 'ACTION', 'income': 'FINANCIAL_INCOME',
    'balancesheet': 'FINANCIAL_BALANCE', 'cashflow': 'FINANCIAL_CASHFLOW',
    'fina_indicator': 'FINANCIAL_INDICATOR', 'daily_basic': 'VALUATION',
    'index_member_all': 'INDUSTRY_MEMBERSHIP', 'sse_announcement': 'CATALYST',
}

DOCUMENTS = (
    ('TUSHARE_PERMISSIONS', 'https://tushare.pro/document/2?doc_id=290'),
    ('TUSHARE_DAILY', 'https://tushare.pro/document/2?doc_id=27'),
    ('TUSHARE_VALUATION', 'https://tushare.pro/document/2?doc_id=32'),
    ('TUSHARE_FINANCIAL', 'https://tushare.pro/document/2?doc_id=79'),
    ('AKSHARE_STATEMENT', 'https://raw.githubusercontent.com/akfamily/akshare/main/docs/introduction.md'),
    ('AKSHARE_TENCENT_IMPLEMENTATION', 'https://raw.githubusercontent.com/akfamily/akshare/main/akshare/stock_feature/stock_hist_tx.py'),
    ('AKSHARE_SINA_IMPLEMENTATION', 'https://raw.githubusercontent.com/akfamily/akshare/main/akshare/stock_fundamental/stock_finance_sina.py'),
    ('SSE_TERMS', 'https://english.sse.com.cn/home/disclaimer/'),
    ('CNINFO_DISCLOSURE_PORTAL', 'https://www.cninfo.com.cn/new/index'),
)


def catalog():
    financial_range = FINANCIAL_START + '..' + HISTORY_END
    financial_buffer = 'ENGINEERING_COLLECTION_BUFFER_NOT_STRATEGY_RULE'
    return [
        {'source': 'EXISTING_INDEXED_QUARANTINED', 'domains': list(dict.fromkeys(API_DOMAINS.values())),
         'access': 'EXISTING_QUARANTINED_RAW_READ_ONLY', 'new_requests': False,
         'authentication': 'KEYCHAIN_REFERENCE_PRESENT_NOT_READ',
         'transport': 'EXISTING_HTTP_UNTRUSTED', 'license': 'BLOCKED_UNVERIFIED',
         'permission': 'Read indexed legacy/wave originals; current gateway collection is a separate source entry',
         'missing': ['supplier identity', 'product/purpose/license', 'historical first visibility', 'revision chains']},
        {'source': 'OWNER_PROVIDED_MONTHLY_GATEWAY',
         'domains': ['PRICE', 'VALUATION', 'FINANCIAL_INCOME', 'FINANCIAL_BALANCE',
                     'FINANCIAL_CASHFLOW', 'FINANCIAL_INDICATOR', 'ACTION'],
         'access': 'OWNER_AUTHORIZED_EXACT_ENDPOINT_EXISTING_KEYCHAIN_QUARANTINE_READ',
         'endpoint': 'http://118.89.117.77:8030/', 'collection_authorized': True,
         'authentication': 'OWNER_ORIGINAL_KEYCHAIN_REUSE_AUTHORIZED_EXISTING_CREDENTIAL_ONLY',
         'permission': 'Owner authorized existing Keychain reuse and read-only requests to this exact endpoint for the exact-three scope',
         'provider_identity': 'UNVERIFIED_NOT_ESTABLISHED_AS_OFFICIAL_TUSHARE',
         'license': 'UNVERIFIED_OWNER_LOCAL_QUARANTINE_ONLY',
         'transport': 'UNVERIFIED_OWNER_HTTP_EXCEPTION', 'historical_visibility_proven': False,
         'provider_license_proven_by_owner_authorization': False,
         'api_permission_state': 'UNVERIFIED_IP_LIMIT_DOES_NOT_ESTABLISH_PERMISSION_DENIAL',
         'new_requests': False, 'collection_status': 'STOPPED_AFTER_IP_CONCURRENCY_LIMIT_NO_AUTOMATIC_RETRY',
         'observed_capture': {'evidence_ref': 'gateway-batch-01/attempts.json',
                              'attempts': 21, 'successful_batches': 7, 'api_errors': 14,
                              'captured_rows': 17992, 'api_error_reason': 'IP_CONCURRENCY_LIMIT',
                              'price_valuation_request_range': '2016-01-01..2026-09-30',
                              'financial_request_range': '2019-01-01..2026-09-30'},
         'time_range_requested': 'price/valuation' + HISTORY_START + '..' + HISTORY_END + '; financial' + financial_range,
         'financial_range_semantics': financial_buffer,
         'missing': ['supplier identity and actual product/purpose license', 'verified transport integrity',
                     'IP concurrency resolution', 'API entitlement beyond successful responses',
                     'historical first visibility and revision chains']},
        {'source': 'TUSHARE_PRO', 'domains': ['PRICE', 'CALENDAR', 'FINANCIAL_INCOME',
         'FINANCIAL_BALANCE', 'FINANCIAL_CASHFLOW', 'FINANCIAL_INDICATOR', 'VALUATION',
         'ACTION', 'STATUS', 'INDUSTRY_MEMBERSHIP', 'BENCHMARK'],
         'access': 'DOCUMENTATION_ONLY_AUTH_REQUIRED', 'new_requests': False,
         'authentication': 'TOKEN_REQUIRED_NOT_ACCESSED', 'license': 'PRODUCT_ENTITLEMENT_UNVERIFIED',
         'docs': [u for n, u in DOCUMENTS if n.startswith('TUSHARE')],
         'time_range_requested': 'price/valuation' + HISTORY_START + '..' + HISTORY_END + '; financial' + financial_range,
         'financial_range_semantics': financial_buffer,
         'missing': ['actual account/product entitlement', 'announcement separate entitlement',
                     'historical versions/first visibility; points alone do not prove these']},
        {'source': 'TENCENT_PUBLIC_RAW_PRICE', 'domains': ['PRICE'],
         'access': 'BOUNDED_UNAUTHENTICATED_PUBLIC_RESEARCH_READ', 'new_requests': True,
         'endpoint': 'https://proxy.finance.qq.com/ifzqgtimg/appstock/app/newfqkline/get',
         'docs': [DOCUMENTS[5][1]], 'time_range_requested': '2016-01-01..2026-09-30 exact-three, yearly <=640 rows',
         'license': 'PUBLIC_RESEARCH_ACCESS_UPSTREAM_LICENSE_UNVERIFIED',
         'missing': ['historical first visibility/revisions', 'verified volume/amount scales',
                     'actions/status', 'valuation', 'upstream use/retention/redistribution rights']},
        {'source': 'SINA_PUBLIC_FINANCIAL',
         'domains': ['FINANCIAL_INCOME', 'FINANCIAL_BALANCE', 'FINANCIAL_CASHFLOW', 'FINANCIAL_INDICATOR'],
         'access': 'BOUNDED_UNAUTHENTICATED_PUBLIC_RESEARCH_READ', 'new_requests': True,
         'endpoint': 'https://quotes.sina.cn/cn/api/openapi.php/CompanyFinanceService.getFinanceReport2022',
         'docs': [DOCUMENTS[6][1]], 'time_range_requested': financial_range + ' report periods, exact-three',
         'financial_range_semantics': financial_buffer,
         'license': 'PUBLIC_RESEARCH_ACCESS_UPSTREAM_LICENSE_UNVERIFIED',
         'missing': ['issuer-original reconciliation', 'full revision chain', 'historical first visibility',
                     'units and YTD/quarter method', 'upstream product/purpose rights']},
        {'source': 'CNINFO_ISSUER_DISCLOSURES', 'domains': ['CATALYST', 'FINANCIAL_INCOME',
         'FINANCIAL_BALANCE', 'FINANCIAL_CASHFLOW', 'STATUS', 'ACTION'],
         'access': 'BOUNDED_PUBLIC_DISCLOSURE_QUERY_AND_ISSUER_DOCUMENT_READ', 'new_requests': True,
         'endpoint': 'https://www.cninfo.com.cn/new/hisAnnouncement/query',
         'docs': ['https://www.cninfo.com.cn/new/index'],
         'time_range_requested': financial_range + ' exact-three, bounded first page annual reports; <=2 PDFs/security',
         'financial_range_semantics': financial_buffer,
         'license': 'PUBLIC_DISCLOSURE_PRIVATE_REVIEW_NO_REDISTRIBUTION_PERMISSION_UNVERIFIED',
         'missing': ['all financial quarter originals/revisions', 'first-visible chain',
                     'full status/action/catalyst history', 'unextracted PDF financial numbers']},
        {'source': 'SSE_PRIMARY', 'domains': ['CALENDAR', 'STATUS', 'ACTION', 'CATALYST'],
         'access': 'TERMS_AND_SERVICE_FEASIBILITY_ONLY', 'new_requests': False,
         'docs': ['https://english.sse.com.cn/home/disclaimer/',
                  'https://www.sseinfo.com/services/data/szjr/ggwjfw/'],
         'license': 'REPRODUCTION_RESTRICTION_PRIMARY_TERMS_NO_BULK_DATA_AUTHORITY',
         'missing': ['written permitted use/service license before new bulk securities collection',
                     'complete actual sessions/status/actions', 'first visibility']},
        {'source': 'UNRESOLVED_FULL_FAMILY_DATA',
         'domains': ['VALUATION', 'INDUSTRY_MEMBERSHIP', 'SECTOR_TOTAL_RETURN', 'BENCHMARK', 'UNIVERSE'],
         'access': 'NO_LICENSED_COMPLETE_SOURCE_ESTABLISHED', 'new_requests': False,
         'license': 'UNSET_REQUIRED',
         'missing': ['1260 valid prior valuation observations', 'historical memberships',
                     'sector/benchmark licensed total-return series', 'survivor selection history']},
    ]
